### ISSUE TITLE
Eternal dog

### ISSUE THREAD

**Issue by One-EyedKing** [DoggyCraftDK/MyDog#4] opened 2019-08-23 13:42 UTC
When the dog dies, it's name will stay in the doglist forever and cant be removed

**Comment by Fido2603** [comment] 2019-08-26 14:40
I cannot reproduce this bug on MyDog V0.0.7
Can you send over a copy of your config.yml?

**Comment by One-EyedKing** [comment] 2019-08-26 15:02
Settings:
  ServerName: Your Server
  Debug: false
  ChatPrefix: MyDog
  InstantSaveConfig: true
DogSettings:
  RandomCollarColor: true
  UseLevels: true
  AllowPlayerKillExp: false
  AllowNametagRename: true
  DogNames:
  - Fido
  - Queen
  - King
  - Doggy
  - Charlie
  - Max
  - Milo
  - Ollie
  - Toby
  - Teddy
  - Molly
  - Rosie
  - Bella
  Levels:
    '1':
      Experience: 0
      Health: 20.0
      Damage: 4.0
    '2':
      Experience: 10
      Health: 21.0
      Damage: 5.0
    '3':
      Experience: 100
      Health: 22.0
      Damage: 6.0
    '4':
      Experience: 200
      Health: 23.0
      Damage: 7.0
    '5':
      Experience: 500
      Health: 24.0
      Damage: 8.0
    '6':
      Experience: 1000
      Health: 26.0
      Damage: 11.0
    '7':
      Experience: 2000
      Health: 29.0
      Damage: 13.0
    '8':
      Experience: 3000
      Health: 31.0
      Damage: 15.0
    '9':
      Experience: 4000
      Health: 33.0
      Damage: 17.0
    '10':
      Experience: 5000
      Health: 36.0
      Damage: 20.0
PlayerInteraction:
  LevelUpSound: ENTITY_WOLF_HOWL
  LevelUpString: '&c&l[{chatPrefix}] &r&cHello! Looks like you just teleported away
    from your Dog(s)! They can sadly not find a safe place to stay, so they are staying
    behind for now :( They will be waiting for you where you left them...'
  NewDogString: '&6&l[{chatPrefix}] &r&6Congratulations with your new dog, {dogNameColor}{dogName}&6!'
  DeadDogString: '&c&l[{chatPrefix}] &r&cYour dog, {dogNameColor}{dogName}&c, just
    passed away... {dogNameColor}{dogName}&c lived for {time}{deadDogLevelString}.'
  DeadDogLevelString: ', and got to &4Level {level}&c'
  CommandComehereString: '&6&l[{chatPrefix}] &r&6Come here! Good doggo, {dogNameColor}{dogName}&6!'

**Comment by One-EyedKing** [comment] 2019-08-26 15:04
`Settings:
  ServerName: Your Server
  Debug: false
  ChatPrefix: MyDog
  InstantSaveConfig: true
DogSettings:
  RandomCollarColor: true
  UseLevels: true
  AllowPlayerKillExp: false
  AllowNametagRename: true
  DogNames:
  - Fido
  - Queen
  - King
  - Doggy
  - Charlie
  - Max
  - Milo
  - Ollie
  - Toby
  - Teddy
  - Molly
  - Rosie
  - Bella
  Levels:
    '1':
      Experience: 0
      Health: 20.0
      Damage: 4.0
    '2':
      Experience: 10
      Health: 21.0
      Damage: 5.0
    '3':
      Experience: 100
      Health: 22.0
      Damage: 6.0
    '4':
      Experience: 200
      Health: 23.0
      Damage: 7.0
    '5':
      Experience: 500
      Health: 24.0
      Damage: 8.0
    '6':
      Experience: 1000
      Health: 26.0
      Damage: 11.0
    '7':
      Experience: 2000
      Health: 29.0
      Damage: 13.0
    '8':
      Experience: 3000
      Health: 31.0
      Damage: 15.0
    '9':
      Experience: 4000
      Health: 33.0
      Damage: 17.0
    '10':
      Experience: 5000
      Health: 36.0
      Damage: 20.0
PlayerInteraction:
  LevelUpSound: ENTITY_WOLF_HOWL
  LevelUpString: '&c&l[{chatPrefix}] &r&cHello! Looks like you just teleported away
    from your Dog(s)! They can sadly not find a safe place to stay, so they are staying
    behind for now :( They will be waiting for you where you left them...'
  NewDogString: '&6&l[{chatPrefix}] &r&6Congratulations with your new dog, {dogNameColor}{dogName}&6!'
  DeadDogString: '&c&l[{chatPrefix}] &r&cYour dog, {dogNameColor}{dogName}&c, just
    passed away... {dogNameColor}{dogName}&c lived for {time}{deadDogLevelString}.'
  DeadDogLevelString: ', and got to &4Level {level}&c'
  CommandComehereString: '&6&l[{chatPrefix}] &r&6Come here! Good doggo, {dogNameColor}{dogName}&6!'
`

**Comment by One-EyedKing** [comment] 2019-08-26 15:08
I deleted the dogs in the dogs.yml manually, but there is no way to do this ingame as far as I know

**Comment by Fido2603** [comment] 2019-08-26 18:45
Hm, it might be because of the "instantSave" not working as it should. Try putting it to false. I will try to test it out as well.

**Comment by Fido2603** [comment] 2019-08-26 19:07
Please check if the issue still persists on version 0.0.8, and if it doesn't then please close the issue.
Otherwise I will close the issue in a week. Having the "instantSave" on true should be fine too.

**Closed** 2019-08-27 21:22 UTC
Labels: bug
